services:
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: ruokataisto-reverse-proxy
    depends_on:
      - ruokataisto-frontend
      - ruokataisto-backend
  ruokataisto-backend:
    image: ruokataisto-backend
    build:
      context: ./ruokataisto-backend
      dockerfile: Dockerfile
    volumes:
      - ./ruokataisto-backend/:/usr/src/app
    container_name: ruokataisto-backend

  ruokataisto-frontend:
    image: ruokataisto-frontend
    build:
      context: ./ruokataisto-frontend
      dockerfile: Dockerfile
    volumes:
      - ./ruokataisto-frontend/:/usr/src/app
    container_name: ruokataisto-frontend
    depends_on:
      - ruokataisto-backend
